import {
  Award,
  ArrowDownRight,
  ArrowRight,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Compass,
  ExternalLink,
  Eye,
  FolderKanban,
  Github,
  GraduationCap,
  HandHeart,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Images,
  Info,
  Instagram,
  Leaf,
  Linkedin,
  Mail,
  Menu,
  MoveRight,
  Play,
  Plus,
  Quote,
  Scale,
  Search,
  Send,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  X,
} from "lucide-react";

/** Shared Lucide icons for application and design-system composition. */
export {
  Award,
  ArrowDownRight,
  ArrowRight,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Compass,
  ExternalLink,
  Eye,
  FolderKanban,
  Github,
  GraduationCap,
  HandHeart,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Images,
  Info,
  Instagram,
  Leaf,
  Linkedin,
  Mail,
  Menu,
  MoveRight,
  Play,
  Plus,
  Quote,
  Scale,
  Search,
  Send,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  X,
};
export type { LucideIcon } from "lucide-react";

/** Icon registry prevents icon-package imports from leaking into application data. */
export const navigationIcons = {
  home: Home,
  about: Info,
  projects: FolderKanban,
  impact: HeartPulse,
  gallery: Images,
  volunteer: HandHeart,
  contact: Mail,
} as const;

export type NavigationIconName = keyof typeof navigationIcons;
